InventoryIMS/Controllers/EditsController.cs
using InventoryIMS.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;

namespace InventoryIMS.Controllers
{
    public class EditsController : Controller
    {
        private readonly dbSampleContext _db;
        public EditsController(dbSampleContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {

            List<TblProduct> Products = _db.TblProducts.ToList();
            return View(Products);

        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]

        public IActionResult Create(TblProduct Product)
        {
            if (ModelState.IsValid)
            {

                _db.TblProducts.Add(Product);
                _db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(Product);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            TblProduct Product = _db.TblProducts.Single(x => x.Product_Id == id);
            return View(Product);

        }



        [HttpPost]

        public IActionResult Edit(TblProduct Product)
        {
            if (ModelState.IsValid)
            {

                _db.Entry(Product).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(Product);
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            TblProduct Product = _db.TblProducts.Single(x => x.Product_Id == id);
            return View(Product);
        }


        [HttpPost]
        [ActionName("Delete")]

        public IActionResult Delete(int? id)
        {
            TblProduct Product = _db.TblProducts.Single(x => x.Product_Id == id);
            _db.TblProducts.Remove(Product);
           _db.SaveChanges();
            return RedirectToAction("Index");
        }


        public IActionResult Details(int id)
        {
            TblProduct Product = new TblProduct();
            Product = _db.TblProducts.Single(x => x.Product_Id == id);
            return View(Product);
        }
    }
}

    

InventoryIMS/Controllers/ProductConController.cs
using InventoryIMS.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;

namespace InventoryIMS.Controllers
{
    public class ProductConController : Controller
    {
        private readonly dbSampleContext _db;

        public ProductConController(dbSampleContext db)
        {
            _db = db;

        }
        [HttpGet]
        public IActionResult Product()
        {
            var getrecords = _db.TblProducts.ToList();

            List<TblProduct> tblProducts = new List<TblProduct>();

            foreach (var item in getrecords)
            {



                var tblProduct = new TblProduct()
                {
                    Product_Id = item.Product_Id,
                    Product_Name = item.Product_Name,
                    Product_Price = item.Product_Price,
                    Product_Qty = item.Product_Qty
                };
                tblProducts.Add(tblProduct);
            };

            return View(tblProducts);
        }
    }
}

InventoryIMS/Views/Edits/Create.cshtml
@model InventoryIMS.Models.TblProduct

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>TblProduct</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Product_Name" class="control-label"></label>
                <input asp-for="Product_Name" class="form-control" />
                <span asp-validation-for="Product_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product_Price" class="control-label"></label>
                <input asp-for="Product_Price" class="form-control" />
                <span asp-validation-for="Product_Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product_Qty" class="control-label"></label>
                <input asp-for="Product_Qty" class="form-control" />
                <span asp-validation-for="Product_Qty" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

InventoryIMS/Views/Edits/Delete.cshtml
@model InventoryIMS.Models.TblProduct

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TblProduct</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product_Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product_Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product_Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product_Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product_Qty)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product_Qty)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Product_Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

InventoryIMS/Views/Edits/Details.cshtml
@model InventoryIMS.Models.TblProduct

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>TblProduct</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product_Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product_Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product_Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product_Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product_Qty)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product_Qty)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Product_Id">Edit</a> |
    <a asp-action="Index" class="alert-info">Back to List</a>
</div>

InventoryIMS/Views/Edits/Edit.cshtml
@model InventoryIMS.Models.TblProduct

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>TblProduct</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Product_Id" />
            <div class="form-group">
                <label asp-for="Product_Name" class="control-label"></label>
                <input asp-for="Product_Name" class="form-control" />
                <span asp-validation-for="Product_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product_Price" class="control-label"></label>
                <input asp-for="Product_Price" class="form-control" />
                <span asp-validation-for="Product_Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product_Qty" class="control-label"></label>
                <input asp-for="Product_Qty" class="form-control" />
                <span asp-validation-for="Product_Qty" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

InventoryIMS/Views/Edits/Index.cshtml
@model IEnumerable<InventoryIMS.Models.TblProduct>

    
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}
@* @Html.ActionLink("Logout","Product","ProductCon" )*@

<h6 class=" align-content-lg-start">
    Welcome @Context.Session.GetString("Username" )
</h6>
@*@Context.Session.GetString("Username" )
*@ 

    <a asp-action="Create" class="btn btn-success">Create New</a>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Product_Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Product_Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Product_Qty)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Product_Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Product_Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Product_Qty)
                </td>
                <td>
                    <a asp-action="Edit" class="btn btn-warning" asp-route-id="@item.Product_Id">Edit</a> |
                    <a asp-action="Details" class="btn btn-primary" asp-route-id="@item.Product_Id">Details</a> |
                    <a asp-action="Delete" class="btn btn-danger" asp-route-id="@item.Product_Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>



<div class="navbar-header Pull-left">
    <a asp-action="Product" class="btn btn-danger " asp-controller="ProductCon" >Logout</a>
</div>